/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContextsIndexRouteImport } from './routes/contexts/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as ContextsContextIdRouteImport } from './routes/contexts/$contextId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIndexRoute = ContextsIndexRouteImport.update({
  id: '/contexts/',
  path: '/contexts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsContextIdRoute = ContextsContextIdRouteImport.update({
  id: '/contexts/$contextId',
  path: '/contexts/$contextId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contexts/$contextId': typeof ContextsContextIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/contexts/': typeof ContextsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contexts/$contextId': typeof ContextsContextIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/contexts': typeof ContextsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contexts/$contextId': typeof ContextsContextIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/contexts/': typeof ContextsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contexts/$contextId'
    | '/sessions/$sessionId'
    | '/contexts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contexts/$contextId' | '/sessions/$sessionId' | '/contexts'
  id:
    | '__root__'
    | '/'
    | '/contexts/$contextId'
    | '/sessions/$sessionId'
    | '/contexts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextsContextIdRoute: typeof ContextsContextIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  ContextsIndexRoute: typeof ContextsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/': {
      id: '/contexts/'
      path: '/contexts'
      fullPath: '/contexts/'
      preLoaderRoute: typeof ContextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/$contextId': {
      id: '/contexts/$contextId'
      path: '/contexts/$contextId'
      fullPath: '/contexts/$contextId'
      preLoaderRoute: typeof ContextsContextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextsContextIdRoute: ContextsContextIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  ContextsIndexRoute: ContextsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
