/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas/$ideaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/ideas': typeof IdeasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ideas/$ideaId' | '/sessions/$sessionId' | '/ideas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ideas/$ideaId' | '/sessions/$sessionId' | '/ideas'
  id: '__root__' | '/' | '/ideas/$ideaId' | '/sessions/$sessionId' | '/ideas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
